### ISSUE TITLE
Refer Multiple dictionaries - Add binding to add_dic

### ISSUE THREAD

**Issue by jaideeppatel** [blatinier/pyhunspell#30]
Hi Blatiner,

As per the instructions and documentation, below is the code to run Hunspell in python:

import hunspell
hobj = hunspell.HunSpell('/usr/share/hunspell/en_US.dic', '/usr/share/hunspell/en_US.aff')

Here hobj - will refer to the en_US dictionary.
I have a need where I want my hunspell script to lookup multiple dictionaries and provide suggestions for the input word.
for example, if I have 3 dictionary files, then is there is way, that pyHunspell can look up all the 3 dictionaries and provide me the ordered suggestions? Could you please provide any suggestions no how can this be achieved? I do not know what changes could be made to enable such a feature.
Your insights on this would be really helpful.
Request you to please look into this and loo forward to hearing from you!

Regards,
Jaideep Patel

**Comment by blatinier** [comment]
It's not possible to do it with no work currently. And I don't know if it fits the purpose of pyhunspell either, since it's just a wrapper around hunspell, but why not someday...

As for solutions, here some you could try : 
- See if it's possible to merge dic & aff files to create the one you would like. I don't really know the exact structure of these files so it requires a bit of investigation on the potential problems it raises (like word collisions, non easily mergable structures…)
- You could wrap the all stuff in a class which hold the needed dic and iterate on dic each time you requires an operation and return the best/merged result. The problem here is in defining the merging method of course… It depends on the methods you intend to use and the reason why you do it :)

If you find a solution, to this problem please give me a feedback so I can document it in the project, or even implement it if it fit right in the lib.

Benoît L.

**Comment by PanderMusubi** [comment]
I see the value for using a medical dictionary in addition to a dict and affix for the same language. This is supported in the API of Hunspell. When using dictionaries and affix files of different languages, you risk a lot of false positives or false negatives.

**Comment by jaideeppatel** [comment]
Hi PanderMusubi,

Can you please point me to the API that you are referring to? and if there are any instructions to use the API that would be great.

Regards,
Jaideep Patel

**Comment by blatinier** [comment]
@jaideeppatel Pander refers to this the hunspell3.pdf [here](https://sourceforge.net/projects/hunspell/files/Hunspell/Documentation/)
@PanderMusubi It seems that the C header file (.h) does not expose add_dic, but the cpp one (.hxx) does. Unfortunately it means for me to read a lot of stuff to get this together, I'm not really used to Cpp/Python bindings... to say the less :)
If you have a good starting point I would happily dig into it. But for now I'm a bit drowned into SWIG/boost/cffi/ctypes/pyrex/cython/…
Any good and clear starting point would but a huge help here. I'll continue to dig in the mean time.

**Comment by PanderMusubi** [comment]
If you have the patience, wait for Hunspell 2.0 is out with improved language binding possibilities. Will take about five months from now (safe estimation).

**Comment by blatinier** [comment]
Hum… and how much more before it gets shipped in Debian/Ubuntu/Centos/…? I don't know if waiting is the best thing to do here, or I misunderstood. Any other suggestion?
