### ISSUE TITLE
Trouble with installing Hunspell

### ISSUE THREAD

**Issue by theasder** [blatinier/pyhunspell#37]
Tried to clone repository and install from it and received error:    

    $ python setup.py install
    /anaconda3/lib/python3.6/distutils/extension.py:131: UserWarning: Unknown Extension options: 'compile_args', 'macros'
      warnings.warn(msg)
    running install
    running build
    running build_ext
    building 'hunspell' extension
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I/usr/local/Cellar/hunspell/1.6.2/include/hunspell/ -I/anaconda3/include/python3.6m -c hunspell.cpp -o build/temp.macosx-10.7-x86_64-3.6/hunspell.o
    hunspell.cpp:144:30: warning: 'spell' is deprecated [-Wdeprecated-declarations]
        retvalue = self->handle->spell(word);
                                 ^
    /usr/local/Cellar/hunspell/1.6.2/include/hunspell/hunspell.hxx:131:20: note: 'spell' has been explicitly marked
          deprecated here
      H_DEPRECATED int spell(const char* word, int* info = NULL, char** root = NULL);
                       ^
    hunspell.cpp:164:31: warning: 'suggest' is deprecated [-Wdeprecated-declarations]
        num_slist = self->handle->suggest(&slist, word);
                                  ^
    /usr/local/Cellar/hunspell/1.6.2/include/hunspell/hunspell.hxx:141:20: note: 'suggest' has been explicitly marked
          deprecated here
      H_DEPRECATED int suggest(char*** slst, const char* word);
                       ^
    hunspell.cpp:175:19: warning: 'free_list' is deprecated [-Wdeprecated-declarations]
        self->handle->free_list(&slist, num_slist);
                      ^
    /usr/local/Cellar/hunspell/1.6.2/include/hunspell/hunspell.hxx:155:21: note: 'free_list' has been explicitly marked
          deprecated here
      H_DEPRECATED void free_list(char*** slst, int n);
                        ^
    hunspell.cpp:193:31: warning: 'analyze' is deprecated [-Wdeprecated-declarations]
        num_slist = self->handle->analyze(&slist, word);
                                  ^
    /usr/local/Cellar/hunspell/1.6.2/include/hunspell/hunspell.hxx:164:20: note: 'analyze' has been explicitly marked
          deprecated here
      H_DEPRECATED int analyze(char*** slst, const char* word);
                       ^
    hunspell.cpp:204:19: warning: 'free_list' is deprecated [-Wdeprecated-declarations]
        self->handle->free_list(&slist, num_slist);
                      ^
    /usr/local/Cellar/hunspell/1.6.2/include/hunspell/hunspell.hxx:155:21: note: 'free_list' has been explicitly marked
          deprecated here
      H_DEPRECATED void free_list(char*** slst, int n);
                        ^
    hunspell.cpp:222:31: warning: 'stem' is deprecated [-Wdeprecated-declarations]
        num_slist = self->handle->stem(&slist, word);
                                  ^
    /usr/local/Cellar/hunspell/1.6.2/include/hunspell/hunspell.hxx:168:20: note: 'stem' has been explicitly marked
          deprecated here
      H_DEPRECATED int stem(char*** slst, const char* word);
                       ^
    hunspell.cpp:233:19: warning: 'free_list' is deprecated [-Wdeprecated-declarations]
        self->handle->free_list(&slist, num_slist);
                      ^
    /usr/local/Cellar/hunspell/1.6.2/include/hunspell/hunspell.hxx:155:21: note: 'free_list' has been explicitly marked
          deprecated here
      H_DEPRECATED void free_list(char*** slst, int n);
                        ^
    hunspell.cpp:251:31: warning: 'generate' is deprecated [-Wdeprecated-declarations]
        num_slist = self->handle->generate(&slist, word1, word2);
                                  ^
    /usr/local/Cellar/hunspell/1.6.2/include/hunspell/hunspell.hxx:181:20: note: 'generate' has been explicitly marked
          deprecated here
      H_DEPRECATED int generate(char*** slst, const char* word, const char* word2);
                       ^
    hunspell.cpp:263:19: warning: 'free_list' is deprecated [-Wdeprecated-declarations]
        self->handle->free_list(&slist, num_slist);
                      ^
    /usr/local/Cellar/hunspell/1.6.2/include/hunspell/hunspell.hxx:155:21: note: 'free_list' has been explicitly marked
          deprecated here
      H_DEPRECATED void free_list(char*** slst, int n);
                        ^
    hunspell.cpp:282:31: warning: 'generate' is deprecated [-Wdeprecated-declarations]
        num_slist = self->handle->generate(&slist, word1, &desc, 1);
                                  ^
    /usr/local/Cellar/hunspell/1.6.2/include/hunspell/hunspell.hxx:191:20: note: 'generate' has been explicitly marked
          deprecated here
      H_DEPRECATED int generate(char*** slst, const char* word, char** desc, int n);
                       ^
    hunspell.cpp:294:19: warning: 'free_list' is deprecated [-Wdeprecated-declarations]
        self->handle->free_list(&slist, num_slist);
                      ^
    /usr/local/Cellar/hunspell/1.6.2/include/hunspell/hunspell.hxx:155:21: note: 'free_list' has been explicitly marked
          deprecated here
      H_DEPRECATED void free_list(char*** slst, int n);
                        ^
    11 warnings generated.
    creating build/lib.macosx-10.7-x86_64-3.6
    g++ -bundle -undefined dynamic_lookup -L/anaconda3/lib -arch x86_64 -L/anaconda3/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.6/hunspell.o -L/anaconda3/lib -lhunspell -o build/lib.macosx-10.7-x86_64-3.6/hunspell.cpython-36m-darwin.so
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
    ld: library not found for -lhunspell
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'g++' failed with exit status 1

**Comment by blatinier** [comment]
"ld: library not found for -lhunspell"
Did you installed libhunspell-dev?If yes please provide os, os version, python version.
-------- Message d'origine --------De : theasder <notifications@github.com> Date : 25/12/2017  11:04  (GMT-03:00) À : blatinier/pyhunspell <pyhunspell@noreply.github.com> Cc : Subscribed <subscribed@noreply.github.com> Objet : [blatinier/pyhunspell] Trouble with installing Hunspell (#37) 
Tried to clone repository and install from it and received error:
$ python setup.py install
/anaconda3/lib/python3.6/distutils/extension.py:131: UserWarning: Unknown Extension options: 'compile_args', 'macros'
  warnings.warn(msg)
running install
running build
running build_ext
building 'hunspell' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I/usr/local/Cellar/hunspell/1.6.2/include/hunspell/ -I/anaconda3/include/python3.6m -c hunspell.cpp -o build/temp.macosx-10.7-x86_64-3.6/hunspell.o
hunspell.cpp:144:30: warning: 'spell' is deprecated [-Wdeprecated-declarations]
    retvalue = self->handle->spell(word);
                             ^
/usr/local/Cellar/hunspell/1.6.2/include/hunspell/hunspell.hxx:131:20: note: 'spell' has been explicitly marked
      deprecated here
  H_DEPRECATED int spell(const char* word, int* info = NULL, char** root = NULL);
                   ^
hunspell.cpp:164:31: warning: 'suggest' is deprecated [-Wdeprecated-declarations]
    num_slist = self->handle->suggest(&slist, word);
                              ^
/usr/local/Cellar/hunspell/1.6.2/include/hunspell/hunspell.hxx:141:20: note: 'suggest' has been explicitly marked
      deprecated here
  H_DEPRECATED int suggest(char*** slst, const char* word);
                   ^
hunspell.cpp:175:19: warning: 'free_list' is deprecated [-Wdeprecated-declarations]
    self->handle->free_list(&slist, num_slist);
                  ^
/usr/local/Cellar/hunspell/1.6.2/include/hunspell/hunspell.hxx:155:21: note: 'free_list' has been explicitly marked
      deprecated here
  H_DEPRECATED void free_list(char*** slst, int n);
                    ^
hunspell.cpp:193:31: warning: 'analyze' is deprecated [-Wdeprecated-declarations]
    num_slist = self->handle->analyze(&slist, word);
                              ^
/usr/local/Cellar/hunspell/1.6.2/include/hunspell/hunspell.hxx:164:20: note: 'analyze' has been explicitly marked
      deprecated here
  H_DEPRECATED int analyze(char*** slst, const char* word);
                   ^
hunspell.cpp:204:19: warning: 'free_list' is deprecated [-Wdeprecated-declarations]
    self->handle->free_list(&slist, num_slist);
                  ^
/usr/local/Cellar/hunspell/1.6.2/include/hunspell/hunspell.hxx:155:21: note: 'free_list' has been explicitly marked
      deprecated here
  H_DEPRECATED void free_list(char*** slst, int n);
                    ^
hunspell.cpp:222:31: warning: 'stem' is deprecated [-Wdeprecated-declarations]
    num_slist = self->handle->stem(&slist, word);
                              ^
/usr/local/Cellar/hunspell/1.6.2/include/hunspell/hunspell.hxx:168:20: note: 'stem' has been explicitly marked
      deprecated here
  H_DEPRECATED int stem(char*** slst, const char* word);
                   ^
hunspell.cpp:233:19: warning: 'free_list' is deprecated [-Wdeprecated-declarations]
    self->handle->free_list(&slist, num_slist);
                  ^
/usr/local/Cellar/hunspell/1.6.2/include/hunspell/hunspell.hxx:155:21: note: 'free_list' has been explicitly marked
      deprecated here
  H_DEPRECATED void free_list(char*** slst, int n);
                    ^
hunspell.cpp:251:31: warning: 'generate' is deprecated [-Wdeprecated-declarations]
    num_slist = self->handle->generate(&slist, word1, word2);
                              ^
/usr/local/Cellar/hunspell/1.6.2/include/hunspell/hunspell.hxx:181:20: note: 'generate' has been explicitly marked
      deprecated here
  H_DEPRECATED int generate(char*** slst, const char* word, const char* word2);
                   ^
hunspell.cpp:263:19: warning: 'free_list' is deprecated [-Wdeprecated-declarations]
    self->handle->free_list(&slist, num_slist);
                  ^
/usr/local/Cellar/hunspell/1.6.2/include/hunspell/hunspell.hxx:155:21: note: 'free_list' has been explicitly marked
      deprecated here
  H_DEPRECATED void free_list(char*** slst, int n);
                    ^
hunspell.cpp:282:31: warning: 'generate' is deprecated [-Wdeprecated-declarations]
    num_slist = self->handle->generate(&slist, word1, &desc, 1);
                              ^
/usr/local/Cellar/hunspell/1.6.2/include/hunspell/hunspell.hxx:191:20: note: 'generate' has been explicitly marked
      deprecated here
  H_DEPRECATED int generate(char*** slst, const char* word, char** desc, int n);
                   ^
hunspell.cpp:294:19: warning: 'free_list' is deprecated [-Wdeprecated-declarations]
    self->handle->free_list(&slist, num_slist);
                  ^
/usr/local/Cellar/hunspell/1.6.2/include/hunspell/hunspell.hxx:155:21: note: 'free_list' has been explicitly marked
      deprecated here
  H_DEPRECATED void free_list(char*** slst, int n);
                    ^
11 warnings generated.
creating build/lib.macosx-10.7-x86_64-3.6
g++ -bundle -undefined dynamic_lookup -L/anaconda3/lib -arch x86_64 -L/anaconda3/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.6/hunspell.o -L/anaconda3/lib -lhunspell -o build/lib.macosx-10.7-x86_64-3.6/hunspell.cpython-36m-darwin.so
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
ld: library not found for -lhunspell
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'g++' failed with exit status 1


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/blatinier/pyhunspell","title":"blatinier/pyhunspell","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/blatinier/pyhunspell"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Trouble with installing Hunspell (#37)"}],"action":{"name":"View Issue","url":"https://github.com/blatinier/pyhunspell/issues/37"}}}

**Comment by theasder** [comment]
I had trouble with installing libhunspell-dev on my OS X 10.12.3.

**Comment by blatinier** [comment]
Unless you solve your problem installing libhunspell-dev, there is no way you can install pyhunspell.
