### ISSUE TITLE
comparison to other hunspell python packages?

### ISSUE THREAD

**Issue by louis-langholtz** [blatinier/pyhunspell#43]
Thank you for making your fork available! Hope my adding this issue is okay...

I'm hoping to better understand where it fits in, in a broader sense, and had the following question come up for me: What's the difference between this code and other hunspell for python packages?

I ask because I'd googled for a python package to use hunspell and found [this package](https://pypi.python.org/pypi/hunspell) and also [CyHunspell](https://pypi.python.org/pypi/CyHunspell) listed on [PyPI](https://pypi.python.org/pypi). Seems there's others too.

Not sure if you're interested in addressing this but I can imagine this being helpful for others too if explained like in your README.md file. The CyHunspell project seems in a similar situation.

Ultimately, I'm looking for a more efficient way of using `hunspell` from Python than using `subprocess.Popen`. I'm not sure which package to use and not sure how to compare them either. Hoping someone like yourself who has authored such a package could help with that.

Thanks again!

**Comment by blatinier** [comment]
It's totally ok to open issues ;)
The first package you linked is this one. "Pip install hunspell" and cloning this repo then "python setup.py install" result in the same :) each tag here is a version on pypi.
I don't know about the cyhunspell package. But about your question with popen, none of these two packages use it. We both bind directly to the cpp hunspell code. Cyhunspell seems to add some caching at the python level which can bring better or worse performances depending on your usage.
You should also see if it's alive but it looks decently active (last commit 3 months ago).
I hope I answered everything. Feel free to ask more if necessary.

**Comment by louis-langholtz** [comment]
Thank you for your response and for confirming my understanding of the relationship between these Python packages and the GitHub projects.

Sounds like both packages are similarly meant to provide directly linked executable access to the hunspell binary library file but that you're not certain about the differences beyond the added caching that the Cyhunspell package uses.

As for differences that I having been finding (and am learning about while writing this) between the two packages:
- Cyhunspell calls itself a wrapper while your package calls itself a module or a set of bindings. I don't know Python well enough however to feel certain whether they are the same things (whether a wrapper for Python is the same as a set of bindings for Python). They do sound like they'd do the same thing.
- When Cyhunspell is installed, the python `site-packages` directory will show a sub-directory that pattern matches `CyHunspell-*` (specifically `CyHunspell-1.2.1.dist-info` for release 1.2.1). When your package is installed the sub-directory for it will be like `hunspell-*` (specifically `hunspell-0.5.3.dist-info` for release 0.5.3).
- From within python, one can confirm `hunspell-0.5.3` is installed using the following code and finding `hunspell==0.5.3` in the output (presumably confirming CyHunspell is installed means finding something more like `CyHunspell-*`):
```python
import pip
sorted(["%s==%s" % (i.key, i.version) for i in pip.get_installed_distributions()])
```
- At this time, Cyhunspell's `hunspell.cpp` file is 10255 lines long, yours is 555 lines long.
- Your C++ code is easier for me to follow and in my opinion looks much cleaner.

I ran into problems when trying to install these packages and saw issues already filed about those problems. Then I wasn't sure what I actually had installed until I learned about and looked into the python `site-packages` directory and also the above mentioned installed packages listing mechanism.

Anyways, hope this provides some insight into questions new users (like me) might have on how your package compares to other hunspell python packages and also some info that may be helpful to add (like to the README.md file) for your repository/package.

**Comment by blatinier** [comment]
The cpp code of Cyhunspell is auto-generated through Cython. In fact the maintainer(s) write the `.pyx` which is Cython (something in-between python and C) and then it's "transpiled" (understand translated) to C++. And like any other auto-generated code, it's kind of ugly :)
But that's not what's the persons read and maintain so nothing to be afraid of. 

The packages names are not that relevant either, the pypi policy on package names is "first arrived first served". There is no check on which package is best suited for a task or even if it's related. If the name was available you could register a package named "linux" which is about anything but linux. There is no authentication and no contact done with the linux "hunspell" program, they probably don't care about us since our package are just "another language binding".

As for the difference between binding and wrapper, I would say that my package is a pure binding only meant to allow users to call `libhunspell` methods through python, maybe with some syntax sugar, but nothing else while `Cyhunspell` is a binding *and* a wrapper since it does the binding job, and wraps the whole thing to add some caching logic with `cacheman`. You should ask them about there specificities since I didn't really dug into there package.

And with this comment I close the issue.
